version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./:/data
    expose:
      - 6379
    command:
      - redis-server --appendonly yes
  app:
    build: .